### ISSUE TITLE
bot wont start

### ISSUE THREAD

**Issue by LeviTheOtaku** [MrFums/Valbot#17]
``` ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "C:\Users\Levi\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 305, in <module>    _win_os_check()
  File "C:\Users\Levi\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\Levi\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "D:\Desktop\Valbot\bot.py", line 14, in <module>
    from pycaw.pycaw import AudioUtilities
  File "C:\Users\Levi\AppData\Local\Programs\Python\Python38\lib\site-packages\pycaw\pycaw.py", line 10, in <module>
    import comtypes
  File "C:\Users\Levi\AppData\Local\Programs\Python\Python38\lib\site-packages\comtypes\__init__.py", line 1176, in <module>
    class IPersist(IUnknown):
  File "C:\Users\Levi\AppData\Local\Programs\Python\Python38\lib\site-packages\comtypes\__init__.py", line 1180, in IPersist
    COMMETHOD([], HRESULT, 'GetClassID',
  File "C:\Users\Levi\AppData\Local\Programs\Python\Python38\lib\site-packages\comtypes\__init__.py", line 1099, in COMMETHOD
    from comtypes.automation import VARIANT
  File "C:\Users\Levi\AppData\Local\Programs\Python\Python38\lib\site-packages\comtypes\automation.py", line 12, in <module>
    from comtypes import npsupport
  File "C:\Users\Levi\AppData\Local\Programs\Python\Python38\lib\site-packages\comtypes\npsupport.py", line 5, in <module>
    import numpy
  File "C:\Users\Levi\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 305, in <module>    _win_os_check()
  File "C:\Users\Levi\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\Levi\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

**Comment by LeviTheOtaku** [comment]
(im retarded. was on python 3.8.5 instead of 3.8.0)
