### ISSUE TITLE
Error after running bot

### ISSUE THREAD

**Issue by Roloo38** [MrFums/Valbot#61]
Hello, after running the bot i got this error. Any help?

[√] RUNNING LATEST VERSION (1.7.8) OF VALBOT

 [!] BOT WILL BEGIN IN 15 SECONDS

 [!] SCHEDULED TO RESTART EVERY 2 HOURS

 [-] SEARCHING FOR PLAY BUTTON
Traceback (most recent call last):
  File "bot.py", line 818, in <module>
    bot.firststart()
  File "bot.py", line 457, in firststart
    self.playbutton()
  File "bot.py", line 213, in playbutton
    play2 = pyautogui.locateOnScreen("images/play.png", confidence=0.6, grayscale=True)
  File "C:\Users\Roloo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Users\Roloo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyautogui\__init__.py", line 213, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
  File "C:\Users\Roloo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyscreeze\__init__.py", line 360, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
  File "C:\Users\Roloo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyscreeze\__init__.py", line 340, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
  File "C:\Users\Roloo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyscreeze\__init__.py", line 135, in wrapper
    return wrappedFunction(*args, **kwargs)
TypeError: _locateAll_python() got an unexpected keyword argument 'confidence'

D:\Downloads\Valbot-1.7.8 (1)>

**Comment by MrFums** [comment]
Maybe try and reinstall your packages. I will be able to help you much better on the [discord server](https://discord.com/invite/QFC46XKzxU)
